[package]
name = "pastebin"
version = "0.1.0"
authors = ["maholder <code@getbraintree.com>"]

[dependencies]
router = "*"
iron = "*"
rusqlite = "*"
r2d2 = "*"
r2d2_sqlite = "*"
persistent = "*"
uuid = { version = "0.2", features = ["v4"] }
